<a href="https://colab.research.google.com/github/saranyak2521-art/ITA0604-MACHINE-LEARNING-192424409-SARANYA-K/blob/main/DATA_MANIPULATION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
STATISTICS IN NUMPY

In [1]:
import numpy as np

In [2]:
data = np.array([100, 200, 300, 400, 500])
print("Mean:", np.mean(data))

Mean: 300.0


In [3]:
data = np.array([100, 200, 300, 400, 500])
print("Median:", np.median(data))

Median: 300.0


In [4]:
from scipy import stats

data = [10, 20, 20, 20, 30, 40]
print("Mode:", stats.mode(data, keepdims=True).mode[0])

Mode: 20


In [5]:
data = np.array([100, 200, 300, 400, 500])
print("Minimum:", np.min(data))

Minimum: 100


In [6]:
data = np.array([100, 200, 300, 400, 500])
print("Maximum:", np.max(data))

Maximum: 500


In [7]:
data = np.array([100, 200, 300, 400, 500])
print("Range:", np.max(data) - np.min(data))

Range: 400


In [8]:
data = np.array([10, 30, 50, 70, 90])
print("Variance:", np.var(data))

Variance: 800.0


In [9]:
data = np.array([10, 30, 50, 70, 90])
print("Standard Deviation:", round(np.std(data), 2))

Standard Deviation: 28.28


In [10]:
data = np.array([10, 20, 30, 40, 50])

print("25th:", np.percentile(data, 25))
print("50th:", np.percentile(data, 50))
print("75th:", np.percentile(data, 75))

25th: 20.0
50th: 30.0
75th: 40.0


In [11]:
data = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Range:", np.max(data)-np.min(data))
print("Variance:", np.var(data))
print("SD:", round(np.std(data), 2))

Mean: 30.0
Median: 30.0
Minimum: 10
Maximum: 50
Range: 40
Variance: 200.0
SD: 14.14


In [ ]:
RANDOM NUMBERS

In [12]:
import numpy as np

print(np.random.random())

0.5018160608566256


In [13]:
print(np.random.random(5))

[0.94512358 0.94337252 0.40117287 0.63559992 0.93064257]


In [14]:
print(np.random.randint(1, 10))

8


In [15]:
dice = np.random.randint(1, 7)
print("Dice:", dice)

Dice: 1


In [16]:
numbers = np.random.randint(1, 101, 10)
print(numbers)

[28 88 18 25 20 50 96 96 91 48]


In [17]:
students = np.array(["Arun", "Bala", "John", "Priya"])

winner = np.random.choice(students)
print("Winner:", winner)

Winner: Bala


In [18]:
students = np.array(["Arun", "Bala", "John", "Priya", "Ravi"])

print(np.random.choice(students, 2))

['John' 'Arun']


In [19]:
numbers = np.array([1, 2, 3, 4, 5])

np.random.shuffle(numbers)
print(numbers)

[1 4 3 2 5]


In [20]:
np.random.seed(42)

print(np.random.randint(1, 100, 5))

[52 93 15 72 61]


In [21]:
import numpy as np

guess = int(input("Guess dice number (1-6): "))
computer = np.random.randint(1, 7)

print("Computer generated:", computer)

if guess == computer:
    print("Congratulations! Correct guess.")
else:
    print("Try again!")

Guess dice number (1-6): 4
Computer generated: 5
Try again!


In [ ]:
BASIC FILTERING


In [22]:
import numpy as np

marks = np.array([45, 78, 90, 55, 82, 60])
print(marks[marks > 60])

[78 90 82]


In [23]:
print(marks[marks > 70])

[78 90 82]


In [24]:
print(marks[marks < 60])

[45 55]


In [25]:
print(marks[marks >= 60])

[78 90 82 60]


In [26]:
print(marks[marks == 60])

[60]


In [27]:
print(marks[marks != 60])

[45 78 90 55 82]


In [28]:
marks = np.array([45, 78, 90, 55, 82, 60, 70])

result = marks[(marks >= 60) & (marks <= 80)]
print(result)

[78 60 70]


In [29]:
marks = np.array([45, 78, 90, 55, 82, 60, 70])

result = marks[(marks >= 60) & (marks <= 80)]
print(result)

[78 60 70]


In [30]:
result = marks[(marks < 50) | (marks > 80)]
print(result)

[45 90 82]


In [31]:
colors = np.array(["Red", "Blue", "Red", "Green", "Blue"])

print(colors[colors == "Red"])

['Red' 'Red']


In [32]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(numbers[numbers % 2 == 0])

[2 4 6 8]


In [33]:
print(numbers[numbers % 2 != 0])

[1 3 5 7]


In [34]:
marks = np.array([45, 78, 90, 55, 82, 60])

print("Indexing:", marks[2])
print("Filtering:", marks[marks > 80])

Indexing: 90
Filtering: [90 82]


In [35]:
prices = np.array([120, 450, 250, 700, 90, 550, 300])

print("Above 300:", prices[prices > 300])
print("Below 200:", prices[prices < 200])
print("Between 200 and 500:", prices[(prices >= 200) & (prices <= 500)])

Above 300: [450 700 550]
Below 200: [120  90]
Between 200 and 500: [450 250 300]


In [ ]:
ALL TOPICS

In [36]:
import numpy as np
marks = np.array([70, 85, 60, 90, 75])
print(marks)

[70 85 60 90 75]


In [37]:
print(max(marks))

90


In [38]:
print(min(marks))

60


In [39]:
print(sum(marks) / len(marks))

76.0


In [40]:
print(np.mean(marks))

76.0


In [41]:
print(marks[0])
print(marks[2])

70
60


In [42]:
print(marks[-1])
print(marks[-2])

75
90


In [43]:
a = np.array([[10,20,30],
              [40,50,60],
              [70,80,90]])
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [44]:
print(a[0,0])
print(a[1,2])

10
60


In [45]:
print(a[1])

[40 50 60]


In [46]:
print(a[:,1])

[20 50 80]


In [47]:
print(marks[1:4])

[85 60 90]


In [48]:
print(marks[marks > 60])

[70 85 90 75]


In [49]:
print(marks[marks < 80])

[70 60 75]


In [50]:
print(marks[(marks >= 60) & (marks <= 80)])

[70 60 75]


In [51]:
numbers = np.array([1,2,3,4,5,6,7,8])
print(numbers[numbers % 2 == 0])

[2 4 6 8]


In [52]:
print(numbers[numbers % 2 != 0])

[1 3 5 7]


In [53]:
print(marks + 5)

[75 90 65 95 80]


In [54]:
marks[1] = 95
print(marks)

[70 95 60 90 75]


In [55]:
import pandas as pd

data = {"Name":["Arun","Banu","Kumar"],
        "Marks":[75,90,60]}

df = pd.DataFrame(data)
print(df)

    Name  Marks
0   Arun     75
1   Banu     90
2  Kumar     60


In [56]:
import numpy as np

prices = np.random.randint(100, 5001, 20)

print("Original Prices:", prices)
print("First 5:", prices[:5])
print("Last 5:", prices[-5:])

gst_prices = prices * 1.18
print("Prices with 18% GST:", gst_prices)

print("Above 2500:", prices[prices > 2500])
print("Between 1000 and 3000:", prices[(prices >= 1000) & (prices <= 3000)])

print("Minimum:", np.min(prices))
print("Maximum:", np.max(prices))
print("Mean:", np.mean(prices))
print("Median:", np.median(prices))
print("Variance:", np.var(prices))
print("Standard Deviation:", np.std(prices))

print("Total Value:", np.sum(prices))
print("Products above average:", np.sum(prices > np.mean(prices)))

np.savetxt("products.csv", gst_prices, delimiter=",")
print("products.csv saved successfully")

Original Prices: [ 566 4526 3544 3271 3019  230 1785  869 2491 2533 1284 4655 3485 4217
 4943 3004  574 1182 2658 2147]
First 5: [ 566 4526 3544 3271 3019]
Last 5: [3004  574 1182 2658 2147]
Prices with 18% GST: [ 667.88 5340.68 4181.92 3859.78 3562.42  271.4  2106.3  1025.42 2939.38
 2988.94 1515.12 5492.9  4112.3  4976.06 5832.74 3544.72  677.32 1394.76
 3136.44 2533.46]
Above 2500: [4526 3544 3271 3019 2533 4655 3485 4217 4943 3004 2658]
Between 1000 and 3000: [1785 2491 2533 1284 1182 2658 2147]
Minimum: 230
Maximum: 4943
Mean: 2549.15
Median: 2595.5
Variance: 1996767.2275000003
Standard Deviation: 1413.0701424557806
Total Value: 50983
Products above average: 10
products.csv saved successfully


In [57]:
import numpy as np

temperatures = np.random.randint(20, 46, 30)

print("Temperatures:", temperatures)
print("First 7 Days:", temperatures[:7])
print("Day 10:", temperatures[9])
print("Day 20:", temperatures[19])

print("Above 35°C:", temperatures[temperatures > 35])
print("Between 25°C and 30°C:", temperatures[(temperatures >= 25) & (temperatures <= 30)])

print("Hottest:", np.max(temperatures))
print("Coolest:", np.min(temperatures))
print("Average:", np.mean(temperatures))
print("Median:", np.median(temperatures))
print("Variance:", np.var(temperatures))
print("Standard Deviation:", np.std(temperatures))

print("Days above average:", np.sum(temperatures > np.mean(temperatures)))

np.savetxt("temperature.csv", temperatures, delimiter=",")
print("temperature.csv saved successfully")

Temperatures: [35 34 34 38 31 42 39 44 22 24 38 26 40 28 26 37 23 44 33 37 45 28 45 40
 21 39 34 26 31 27]
First 7 Days: [35 34 34 38 31 42 39]
Day 10: 24
Day 20: 37
Above 35°C: [38 42 39 44 38 40 37 44 37 45 45 40 39]
Between 25°C and 30°C: [26 28 26 28 26 27]
Hottest: 45
Coolest: 21
Average: 33.7
Median: 34.0
Variance: 51.41
Standard Deviation: 7.170076708097341
Days above average: 17
temperature.csv saved successfully


In [58]:
import numpy as np

electricity = np.random.randint(100, 801, 12)

print("Monthly Consumption:", electricity)
print("First 3 Months:", electricity[:3])
print("Last Month:", electricity[-1])

bill = electricity * 6
print("Electricity Bill:", bill)

print("Above 500 Units:", electricity[electricity > 500])

print("Minimum:", np.min(electricity))
print("Maximum:", np.max(electricity))
print("Total Annual Consumption:", np.sum(electricity))
print("Average:", np.mean(electricity))
print("Variance:", np.var(electricity))
print("Standard Deviation:", np.std(electricity))

print("Months below average:", np.sum(electricity < np.mean(electricity)))

np.savetxt("electricity.csv", electricity, delimiter=",")
print("electricity.csv saved successfully")

Monthly Consumption: [134 305 180 661 487 101 489 665 205 576 501 655]
First 3 Months: [134 305 180]
Last Month: 655
Electricity Bill: [ 804 1830 1080 3966 2922  606 2934 3990 1230 3456 3006 3930]
Above 500 Units: [661 665 576 501 655]
Minimum: 101
Maximum: 665
Total Annual Consumption: 4959
Average: 413.25
Variance: 42794.854166666664
Standard Deviation: 206.86917161981063
Months below average: 5
electricity.csv saved successfully


In [59]:
import numpy as np

battery = np.random.randint(5, 101, 20)

print("Battery Readings:", battery)
print("First Reading:", battery[0])
print("Fifth Reading:", battery[4])
print("Tenth Reading:", battery[9])
print("Last Reading:", battery[-1])

print("Below 20%:", battery[battery < 20])
print("Between 30% and 70%:", battery[(battery >= 30) & (battery <= 70)])

print("Average:", np.mean(battery))
print("Minimum:", np.min(battery))
print("Maximum:", np.max(battery))
print("Variance:", np.var(battery))
print("Standard Deviation:", np.std(battery))

print("Below Average:", np.sum(battery < np.mean(battery)))
print("Total:", np.sum(battery))

np.savetxt("battery.csv", battery, delimiter=",")
print("battery.csv saved successfully")

Battery Readings: [38 78 66 18 99 52 19 76 82 91 66 44 89 84 86 57 28 30 93 64]
First Reading: 38
Fifth Reading: 99
Tenth Reading: 91
Last Reading: 64
Below 20%: [18 19]
Between 30% and 70%: [38 66 52 66 44 57 30 64]
Average: 63.0
Minimum: 18
Maximum: 99
Variance: 640.9
Standard Deviation: 25.31600284405103
Below Average: 8
Total: 1260
battery.csv saved successfully


In [60]:
import numpy as np

sales = np.random.randint(5000, 50001, 30)

print("Original Sales:", sales)
print("First 7 Days:", sales[:7])
print("Last 7 Days:", sales[-7:])

updated_sales = sales * 1.05
print("Sales after 5% Increase:", updated_sales)

print("Above ₹30,000:", sales[sales > 30000])
print("Between ₹15,000 and ₹25,000:", sales[(sales >= 15000) & (sales <= 25000)])

print("Minimum:", np.min(sales))
print("Maximum:", np.max(sales))
print("Mean:", np.mean(sales))
print("Median:", np.median(sales))
print("Variance:", np.var(sales))
print("Standard Deviation:", np.std(sales))

print("Total Monthly Sales:", np.sum(sales))

np.savetxt("sales.csv", updated_sales, delimiter=",")
print("sales.csv saved successfully")

Original Sales: [13571 44976 43044 45774  7568  7027  7695 10258 27002 44504 38159 18986
 17666 43660  8561 31854 43952 27662 13392 35535 18067 28599 40222 16837
 19039 35818 24115 15965 29538 47530]
First 7 Days: [13571 44976 43044 45774  7568  7027  7695]
Last 7 Days: [16837 19039 35818 24115 15965 29538 47530]
Sales after 5% Increase: [14249.55 47224.8  45196.2  48062.7   7946.4   7378.35  8079.75 10770.9
 28352.1  46729.2  40066.95 19935.3  18549.3  45843.    8989.05 33446.7
 46149.6  29045.1  14061.6  37311.75 18970.35 30028.95 42233.1  17678.85
 19990.95 37608.9  25320.75 16763.25 31014.9  49906.5 ]
Above ₹30,000: [44976 43044 45774 44504 38159 43660 31854 43952 35535 40222 35818 47530]
Between ₹15,000 and ₹25,000: [18986 17666 18067 16837 19039 24115 15965]
Minimum: 7027
Maximum: 47530
Mean: 26885.866666666665
Median: 27332.0
Variance: 179042649.58222225
Standard Deviation: 13380.681955050806
Total Monthly Sales: 806576
sales.csv saved successfully


In [ ]:
import numpy as np

speed = np.random.randint(20, 151, 25)

print("Speed Readings:", speed)
print("First 5 Speeds:", speed[:5])
print("Alternate Speeds:", speed[::2])

print("Above 100 km/h:", speed[speed > 100])
print("Between 60 and 90 km/h:", speed[(speed >= 60) & (speed <= 90)])

print("Slowest:", np.min(speed))
print("Fastest:", np.max(speed))
print("Average:", np.mean(speed))
print("Median:", np.median(speed))
print("Variance:", np.var(speed))
print("Standard Deviation:", np.std(speed))

print("Vehicles above 80 km/h:", np.sum(speed > 80))

np.savetxt("vehicle_speed.csv", speed, delimiter=",")
print("vehicle_speed.csv saved successfully")

In [61]:
import numpy as np

orders = np.random.randint(100, 2001, 25)

print("Original Orders:", orders)
print("First 5 Orders:", orders[:5])
print("Last 5 Orders:", orders[-5:])

final_orders = orders * 1.05
print("Orders after 5% Service Charge:", final_orders)

print("Above ₹1000:", orders[orders > 1000])
print("Below ₹500:", orders[orders < 500])

print("Smallest:", np.min(orders))
print("Largest:", np.max(orders))
print("Mean:", np.mean(orders))
print("Median:", np.median(orders))
print("Variance:", np.var(orders))
print("Standard Deviation:", np.std(orders))

print("Total Revenue:", np.sum(final_orders))
print("Customers above average:", np.sum(orders > np.mean(orders)))

np.savetxt("restaurant_orders.csv", final_orders, delimiter=",")
print("restaurant_orders.csv saved successfully")

Original Orders: [1060 1862  712 1585  742 1892 1128 1341  602  866  497  970  894  492
  306 1138 1981 1677  991 1584 1814 1698  963  842 1364]
First 5 Orders: [1060 1862  712 1585  742]
Last 5 Orders: [1814 1698  963  842 1364]
Orders after 5% Service Charge: [1113.   1955.1   747.6  1664.25  779.1  1986.6  1184.4  1408.05  632.1
  909.3   521.85 1018.5   938.7   516.6   321.3  1194.9  2080.05 1760.85
 1040.55 1663.2  1904.7  1782.9  1011.15  884.1  1432.2 ]
Above ₹1000: [1060 1862 1585 1892 1128 1341 1138 1981 1677 1584 1814 1698 1364]
Below ₹500: [497 492 306]
Smallest: 306
Largest: 1981
Mean: 1160.04
Median: 1060.0
Variance: 231883.6384
Standard Deviation: 481.5429766905546
Total Revenue: 30451.05
Customers above average: 10
restaurant_orders.csv saved successfully


In [62]:
import numpy as np

rainfall = np.random.randint(0, 201, 30)

print("Rainfall:", rainfall)
print("Days 1-10:", rainfall[:10])
print("Final 5 Days:", rainfall[-5:])

print("Above 100 mm:", rainfall[rainfall > 100])
print("Below 20 mm:", rainfall[rainfall < 20])

print("Minimum:", np.min(rainfall))
print("Maximum:", np.max(rainfall))
print("Average:", np.mean(rainfall))
print("Median:", np.median(rainfall))
print("Variance:", np.var(rainfall))
print("Standard Deviation:", np.std(rainfall))

print("Total Rainfall:", np.sum(rainfall))
print("Days above average:", np.sum(rainfall > np.mean(rainfall)))

np.savetxt("rainfall.csv", rainfall, delimiter=",")
print("rainfall.csv saved successfully")

Rainfall: [ 51  95 131 150 142 170  28  35  12 159  70 186  85  27  65 169  44  61
 184 133  27  27 107  43  83  29 189  74 127  91]
Days 1-10: [ 51  95 131 150 142 170  28  35  12 159]
Final 5 Days: [ 29 189  74 127  91]
Above 100 mm: [131 150 142 170 159 186 169 184 133 107 189 127]
Below 20 mm: [12]
Minimum: 12
Maximum: 189
Average: 93.13333333333334
Median: 84.0
Variance: 3103.3822222222225
Standard Deviation: 55.708008600399836
Total Rainfall: 2794
Days above average: 13
rainfall.csv saved successfully


In [63]:
import numpy as np

production = np.random.randint(50, 501, (4, 7))

print("Production Array:")
print(production)

print("Machine 1:", production[0])
print("Day 3:", production[:, 2])
print("Machine 3 Day 5:", production[2, 4])

print("Production above 300:", production[production > 300])

print("Total of Each Machine:", np.sum(production, axis=1))
print("Total of Each Day:", np.sum(production, axis=0))

print("Minimum:", np.min(production))
print("Maximum:", np.max(production))
print("Mean:", np.mean(production))
print("Standard Deviation:", np.std(production))

print("Values above average:", np.sum(production > np.mean(production)))

np.savetxt("factory_production.csv", production, delimiter=",")
print("factory_production.csv saved successfully")

Production Array:
[[280 239 274 434 426 332 495]
 [170 165 282 308 408 247 460]
 [186 367 214 274 356 283 221]
 [201 364 423 209 145 282 229]]
Machine 1: [280 239 274 434 426 332 495]
Day 3: [274 282 214 423]
Machine 3 Day 5: 356
Production above 300: [434 426 332 495 308 408 460 367 356 364 423]
Total of Each Machine: [2480 2040 1901 1853]
Total of Each Day: [ 837 1135 1193 1225 1335 1144 1405]
Minimum: 145
Maximum: 495
Mean: 295.5
Standard Deviation: 95.35965753773598
Values above average: 11
factory_production.csv saved successfully


In [64]:
import numpy as np

data = np.random.randint(1, 1001, 50)

print("Original Data:", data)
print("First 10:", data[:10])
print("Last 10:", data[-10:])
print("Every Second Element:", data[::2])
print("Indexes 5, 10, 15, 20:", data[[5, 10, 15, 20]])

data = data + 100
print("After Adding 100:", data)

data = data * 2
print("After Multiplying by 2:", data)

print("Above 500:", data[data > 500])
print("Between 200 and 600:", data[(data >= 200) & (data <= 600)])
print("Even Numbers:", data[data % 2 == 0])
print("Odd Numbers:", data[data % 2 != 0])

print("Sum:", np.sum(data))
print("Product:", np.prod(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Variance:", np.var(data))
print("Standard Deviation:", np.std(data))

print("25th Percentile:", np.percentile(data, 25))
print("50th Percentile:", np.percentile(data, 50))
print("75th Percentile:", np.percentile(data, 75))

print("Numbers above mean:", np.sum(data > np.mean(data)))

print("Sorted Data:", np.sort(data))

np.save("original_data.npy", data)
np.savetxt("final_data.csv", data, delimiter=",")

print("original_data.npy saved successfully")
print("final_data.csv saved successfully")

Original Data: [113 830 497 442 564 268 510 807 386 387 113 613 625 952  81 699 113   2
 642 220 566 855 997 736 225 385 403 638 130  53 684 730 672 710 416 247
 836 439 203 184 123 401 767 294 280 837 884 610 198 982]
First 10: [113 830 497 442 564 268 510 807 386 387]
Last 10: [123 401 767 294 280 837 884 610 198 982]
Every Second Element: [113 497 564 510 386 113 625  81 113 642 566 997 225 403 130 684 672 416
 836 203 123 767 280 884 198]
Indexes 5, 10, 15, 20: [268 113 699 566]
After Adding 100: [ 213  930  597  542  664  368  610  907  486  487  213  713  725 1052
  181  799  213  102  742  320  666  955 1097  836  325  485  503  738
  230  153  784  830  772  810  516  347  936  539  303  284  223  501
  867  394  380  937  984  710  298 1082]
After Multiplying by 2: [ 426 1860 1194 1084 1328  736 1220 1814  972  974  426 1426 1450 2104
  362 1598  426  204 1484  640 1332 1910 2194 1672  650  970 1006 1476
  460  306 1568 1660 1544 1620 1032  694 1872 1078  606  568  446 1002
 1